### ISSUE TITLE
IOException when running inside a restricted container

### ISSUE THREAD

**Issue by cereda** [nlct/bib2gls#30]
Hi Nicky, hope you are doing well!

Thanks for this amazing tool!

First and foremost, this is not a bug. :wink: We would like to report an interesting scenario where an `IOException` is thrown and `bib2gls` fails.

We are experimenting an `IOException` when running `bib2gls` inside a restricted container (namely, Docker with a seccomp security profile). This is the stack trace:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/sun.nio.ch.FileChannelImpl.<init>(FileChannelImpl.java:132)
	at java.base/sun.nio.ch.FileChannelImpl.open(FileChannelImpl.java:154)
	at java.base/sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:134)
	at java.base/sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:146)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:216)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
	at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3008)
	at com.dickimawbooks.bib2gls.Bib2Gls.parseArgs(Bib2Gls.java:7106)
	at com.dickimawbooks.bib2gls.Bib2Gls.process(Bib2Gls.java:1913)
	at com.dickimawbooks.bib2gls.Bib2Gls.main(Bib2Gls.java:7225)
Caused by: java.io.IOException: Operation not permitted
	at java.base/sun.nio.ch.FileDispatcherImpl.init(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.<clinit>(FileDispatcherImpl.java:38)
	... 11 more
```

It took us a while to find out what was happening. It seems `Files.newBufferedReader` and `Files.newBufferedWriter`  (from NIO2 introduced in Java 7) rely on sockets and thus require at least six more rules on our seccomp profile:

```json
        {
          "name": "flock",
          "action": "SCMP_ACT_ALLOW",
          "args": []
        }, {
          "name": "socket",
          "action": "SCMP_ACT_ALLOW",
          "args": []
        }, {
          "name": "connect",
          "action": "SCMP_ACT_ALLOW",
          "args": []
        }, {
          "name": "getsockname",
          "action": "SCMP_ACT_ALLOW",
          "args": []
        }, {
          "name": "setsockopt",
          "action": "SCMP_ACT_ALLOW",
          "args": []
        }, {
          "name": "socketpair",
          "action": "SCMP_ACT_ALLOW",
          "args": []
        }
```

Since these capabilities may pose significant risks, our engineering team is advising against updating them in the seccomp profile. We are wondering if we could suggest or work together on a different file implementation to stream with.

We also conducted some experiments reverting `newBufferedReader` and `newBufferedWriter` to `FileReader` and `FileWriter` whenever applicable (as seen in the previous version of bib2gls), and the execution raised no errors.

I found occurrences in `bib2gls`, `common`, and `texparserlib`.

Thanks so much!

**Comment by nlct** [comment]
Hi Paulo! Hope all's well with you too. :smiley: 

Thank you for raising this. And there was I thinking that I ought to move over to the more modern `Files.newBufferedReader` and `Files.newBufferedWriter`! They are convenient, especially if a non-default charset is needed, but I'll change them back.

All the best!

**Comment by nlct** [comment]
I've modified the TeX Parser Library so that TeXApp now has two extra methods:
```java
   public BufferedReader createBufferedReader(Path path,
     Charset charset) throws IOException, SecurityException;

   public BufferedWriter createBufferedWriter(Path path,
     Charset charset) throws IOException, SecurityException;
```
(Commit https://github.com/nlct/texparser/commit/ff75de917063f533a1bf98bbedc1e4e6c1961dd0)

I think I've found and replaced all instances of the `java.nio.Files` methods. I've also updated bib2gls (commit https://github.com/nlct/bib2gls/commit/e9d8b2f9596568e747609567d75357ff43776418).

**Comment by cereda** [comment]
That's awesome, Nicky! Thanks so much! :tada:
